### ISSUE TITLE
using validated wrapper on multiple mutations

### ISSUE THREAD

**Issue by dariuscosden** [chpmrc/graphene-validator#1]
I seem to be having troubles using the `@validated` wrapper on more than one mutation. If I decorate only one mutation with it, it works as expected. As soon as I add another, I get the following error:

`AssertionError: Found different types with the same name in the schema: Wrapper, Wrapper.`

**Comment by elchiapp** [comment]
Sorry about the late response. That's interesting, I'll take a look as soon as I can.

**Comment by elchiapp** [comment]
Hey this has been fixed in https://github.com/chpmrc/graphene-validator/commit/91c16a9fce8e58664d0b5cbc704e3eeec0e96861, would you mind testing again? Thank you!

**Comment by elchiapp** [comment]
I'll close this for now, feel free to reopen if you're still getting the same issue.
