### ISSUE TITLE
ValidationError code property not used in error output

### ISSUE THREAD

**Issue by akikoskinen** [chpmrc/graphene-validator#7]
The `ValidationError` class has [a `code` property](https://github.com/chpmrc/graphene-validator/blob/265b9cf38cacbd880f3b1f1c98e3344727dacfc2/graphene_validator/errors.py#L31-L33). But that property isn't used in the errors output as the `code` member, neither for [field specific validation](https://github.com/chpmrc/graphene-validator/blob/265b9cf38cacbd880f3b1f1c98e3344727dacfc2/graphene_validator/decorators.py#L119), nor for the [generic validation](https://github.com/chpmrc/graphene-validator/blob/265b9cf38cacbd880f3b1f1c98e3344727dacfc2/graphene_validator/decorators.py#L138). Instead the stringified version of the exception is used.

Shouldn't the `code` property be used instead, as there is such a thing in the exception class?

**Comment by elchiapp** [comment]
This has been fixed.
